root = "."
tmp_dir = "tmp"

[build]
  # Build the Linux binary into tmp/main
  cmd = "go build -o ./tmp/main ."
  bin = "./tmp/main"
  delay = 300
  include_ext = ["go", "mod", "sum", "tpl", "tmpl", "html"]
  exclude_dir = ["vendor", "tmp", ".git", "testdata", "assets"]
  exclude_regex = ["_test.go"]
  kill_delay = "200ms"
  log = "build-errors.log"
  stop_on_error = false

[color]
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  time = true
  silent = false
  main_only = false

[misc]
  clean_on_exit = false

[proxy]
  enabled = false
  app_port = 0
  proxy_port = 0

[screen]
  clear_on_rebuild = false
  keep_scroll = true
